### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qasimmodo** [will118/arrTorrent#3]
[root@ts arrTorrent]# node server
module.js:457
    throw err;
    ^

Error: Cannot find module '../../secrets'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/arrTorrent/server/ipt/client.js:4:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by will118** [comment]
Hey, I forgot this project was public, it's gotten quite specific to my use case.

Do you know what this repo is for? I don't describe it anywhere that's all. I'm updating the project this weekend (and will add README) but it's basically an rtorrent client, and a node app to proxy the RPC2 of rtorrent. It's also got basic search for IPT tracker where it automatically adds the torrent with most seeders.

To answer your actual question, you need to `cp secrets.json.example secrets.json` and fill it in with real values:
* `"uid"` is IPT `"uid"` cookie key.
* `"passwordHash"` is the `"pass"` cookie key from IPT.
* `"watch_dir"` is where to write torrents, i.e. the directory rtorrent is watching for `.torrent` files to auto-add.
